### ISSUE TITLE
How to use LazyIDA?

### ISSUE THREAD

**Issue by JsHuang** [L4ys/LazyIDA#11]
I installed LazyIDA in IDA 7.0 , then open an executable, but I can't find LazyIDA options in Edit->Plugins。
Is there any detailed doc about how to use it?
Thanks

**Comment by PSR009** [comment]
After copying `LazyIDA.py` into the plugins folder under your IDA Pro installation path.

Restart IDA Pro, you can see `LazyIDA (v1.0.0.3) plugin has been loaded.` on the output window.

Just right-click anywhere inside `IDA View-A` and you can see `Convert` and `Scan format string vulnerabilities` options
