### ISSUE TITLE
是不支持ida7.6还有7.5吗？

### ISSUE THREAD

**Issue by zhefox** [L4ys/LazyIDA#17]
是不支持ida7.6还有7.5吗？

**Comment by L4ys** [comment]
It supports IDA Pro >= 7.0

**Comment by zhefox** [comment]
> It supports IDA Pro >= 7.0

为何我丢入plugins后，并未启用该插件，且在edit->plugins里无法找到该插件的身影

**Comment by L4ys** [comment]
It won't add entries to plugins menu
To use the LazyIDA function, just right-click in the disassembly view or pseudo code view

**Comment by zhefox** [comment]
> It won't add entries to plugins menu To use the LazyIDA function, just right-click in the disassembly view or pseudo code view

一样的，在右键菜单中，我并未找到md中存在的相关功能选项，这是为什么呢

**Comment by L4ys** [comment]
Check your output window of IDA Pro, there should be a message "LazyIDA (v1.0.0.3) plugin has been loaded."
If not, then check if there is an error message.

If none of the above messages appear, you may put the plugin in the wrong directory or your idapython was not configured correctly

**Comment by L4ys** [comment]
A common error is that idapython is using incorrect version of sip, which will cause PyQt5 to fail to load
you may use idapyswitch.exe to set the correct version of python that idapython should use

**Comment by zhefox** [comment]
为何我丢进ida7.6的plugins里面，但实际上ida并未加载出该插件



| |
ZHEFOX
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月08日 00:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [L4ys/LazyIDA] 是不支持ida7.6还有7.5吗？ (Issue #17) |

It supports IDA Pro >= 7.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhefox** [comment]
> 是

修改为from PyQt5 import*,解决了 程序加载问题，然后我该如何操作启用格式化字符串漏洞的检测窗口呢

**Comment by zhefox** [comment]
> > 是
> 
> 修改为from PyQt5 import*,解决了 程序加载问题，然后我该如何操作启用格式化字符串漏洞的检测窗口呢

已解决
